In [1]:
from tensorflow.keras.preprocessing.text import one_hot
#sentesncs
sent =[
    'the glass of milk',
    'the glass of juice',
    'the cup of tea',
    'I am a good boy',
    'I am a good developer',
    'understanding the meaning of words',
    'your videos are good',
]

In [2]:
#Define the vocabukary size
voc_size =10000
#one_hot representation
one_hot_repr=[one_hot(words, voc_size)for words in sent]
one_hot_repr


[[2585, 5487, 2686, 9483],
 [2585, 5487, 2686, 8265],
 [2585, 4903, 2686, 8662],
 [2000, 165, 5370, 8424, 7242],
 [2000, 165, 5370, 8424, 6876],
 [7405, 2585, 2388, 2686, 3884],
 [4094, 3872, 9525, 8424]]

In [7]:
#word embedding representation

from tensorflow.keras.layers import Embedding
#from tensorflow.keras.preprocessing.sequence import pad_sequences
from tensorflow.keras.utils import pad_sequences
from tensorflow.keras.models import Sequential
import numpy as np


In [23]:
sent_len = 8
embedded_docs = pad_sequences(one_hot_repr, padding='pre', maxlen=sent_len)
print(embedded_docs)

[[   0    0    0    0 2585 5487 2686 9483]
 [   0    0    0    0 2585 5487 2686 8265]
 [   0    0    0    0 2585 4903 2686 8662]
 [   0    0    0 2000  165 5370 8424 7242]
 [   0    0    0 2000  165 5370 8424 6876]
 [   0    0    0 7405 2585 2388 2686 3884]
 [   0    0    0    0 4094 3872 9525 8424]]


In [9]:
#feature representation
dim=10


In [19]:
model = Sequential()
model.add(Embedding(voc_size, dim,input_length= sent_len))
model.compile('adam', 'mse')

In [20]:
model.summary()


Model: "sequential_3"

┏━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━┳━━━━━━━━━━━━━━━━━━━━━━━━┳━━━━━━━━━━━━━━━┓
┃ Layer (type)                    ┃ Output Shape           ┃       Param # ┃
┡━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━╇━━━━━━━━━━━━━━━━━━━━━━━━╇━━━━━━━━━━━━━━━┩
│ embedding_3 (Embedding)         │ ?                      │   0 (unbuilt) │
└─────────────────────────────────┴────────────────────────┴───────────────┘

 Total params: 0 (0.00 B)

 Trainable params: 0 (0.00 B)

 Non-trainable params: 0 (0.00 B)

In [28]:
model.predict(embedded_docs)

1/1 ━━━━━━━━━━━━━━━━━━━━ 0s 19ms/step


array([[[ 0.02745439, -0.01399205, -0.04629543, -0.03241153,
         -0.04858331, -0.04115938,  0.02161273, -0.04280281,
         -0.02219296,  0.03642141],
        [ 0.02745439, -0.01399205, -0.04629543, -0.03241153,
         -0.04858331, -0.04115938,  0.02161273, -0.04280281,
         -0.02219296,  0.03642141],
        [ 0.02745439, -0.01399205, -0.04629543, -0.03241153,
         -0.04858331, -0.04115938,  0.02161273, -0.04280281,
         -0.02219296,  0.03642141],
        [ 0.02745439, -0.01399205, -0.04629543, -0.03241153,
         -0.04858331, -0.04115938,  0.02161273, -0.04280281,
         -0.02219296,  0.03642141],
        [-0.04029276, -0.02102621, -0.02535572,  0.00735576,
         -0.01259322, -0.00617657,  0.04027249,  0.00654907,
         -0.02202824, -0.02209838],
        [-0.02547238, -0.04807309, -0.01033432,  0.02324719,
          0.00449008, -0.04312275, -0.01571673, -0.02827513,
          0.01567533,  0.04705436],
        [ 0.00476607, -0.0177124 , -0.02025813, -0.0

In [25]:
embedded_docs[0]

array([   0,    0,    0,    0, 2585, 5487, 2686, 9483], dtype=int32)

In [30]:
model.predict(embedded_docs[0].reshape(1,-1))

1/1 ━━━━━━━━━━━━━━━━━━━━ 0s 38ms/step


array([[[ 0.02745439, -0.01399205, -0.04629543, -0.03241153,
         -0.04858331, -0.04115938,  0.02161273, -0.04280281,
         -0.02219296,  0.03642141],
        [ 0.02745439, -0.01399205, -0.04629543, -0.03241153,
         -0.04858331, -0.04115938,  0.02161273, -0.04280281,
         -0.02219296,  0.03642141],
        [ 0.02745439, -0.01399205, -0.04629543, -0.03241153,
         -0.04858331, -0.04115938,  0.02161273, -0.04280281,
         -0.02219296,  0.03642141],
        [ 0.02745439, -0.01399205, -0.04629543, -0.03241153,
         -0.04858331, -0.04115938,  0.02161273, -0.04280281,
         -0.02219296,  0.03642141],
        [-0.04029276, -0.02102621, -0.02535572,  0.00735576,
         -0.01259322, -0.00617657,  0.04027249,  0.00654907,
         -0.02202824, -0.02209838],
        [-0.02547238, -0.04807309, -0.01033432,  0.02324719,
          0.00449008, -0.04312275, -0.01571673, -0.02827513,
          0.01567533,  0.04705436],
        [ 0.00476607, -0.0177124 , -0.02025813, -0.0